#name: End to End Site Testing

#on:
#    workflow_dispatch:
#    push:
#        branches: ['master']
#
#    pull_request:
#        branches: ['master']
#        types: [opened, reopened]
#
#env:
#    DATABASE_URL: ${{secrets.DATABASE_URL}}
#
#    S3_ADMIN_ACCESS_KEY: ${{secrets.S3_ADMIN_ACCESS_KEY}}
#    S3_ADMIN_SECRET_KEY: ${{secrets.S3_ADMIN_SECRET_KEY}}
#
#    DUMMY_EMAIL: ${{secrets.DUMMY_EMAIL}}
#    DUMMY_PASSWORD: ${{secrets.DUMMY_PASSWORD}}
#
#    APP_STATE: ${{secrets.APP_STATE}}
#
#jobs:
#    build:
#        runs-on: ubuntu-latest
#
#        steps:
#            - uses: actions/checkout@v3
#            - uses: actions/setup-node@v3
#              with:
#                  node-version: '20.x'
#
#            - name: Init Node.js Environment
#              run: npm install
#
#            - name: Init Playwright Environment
#              run: npx playwright install --with-deps
#
#            - name: Build and Test
#              run: |
#                  npm run dbgenerate
#
#                  npm run build
#
#                  node .output/server/index.mjs &
#                  npm run test
#